version: 2
jobs:
  build:
    docker:
      - image: python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            apt-get -qq update && apt-get -y -qq install libtag1-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install cython

      - run:
          name: build cython module
          command: |
            python3 -m venv venv
            . venv/bin/activate
            id
            python3 setup.py build --cython

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
